name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install Packages
        run: npm i

      - name: Check Lint
        run: npm run lint

      - name: Check Buld
        run: npm run build

      - name: Run Tests
        run: npm run test
